In [1]:
import pandas
import re
import numpy as np

In [13]:
vaild=re.compile(r"GEN_(\d+)_relations.json")
vaild.search("GEN_1_relations.json")[1]

'1'

In [18]:
files=["GEN_0_Relations.json","GEN_1_Relations.json"]
vaild=re.compile(r"GEN_(\d+)_Relations.json")
maxigen=0
for file in files:
    igen=int(vaild.search(file)[1])
    print("igen=%d"%igen)
    if igen>maxigen:
        maxigen=igen
igen=maxigen

igen=0
igen=1


In [5]:
def random_sampling_LHS_np(nval,nsamples):
    ###FAST RANDOM USE NUMPY
    ranlist=np.random.random((nsamples,nval))
    jarray=np.mgrid[0:nsamples,0:nval][0]
    for colomn in jarray.T:
        np.random.shuffle(colomn)    
    ranlist=(ranlist+jarray)/nsamples
    return ranlist

In [13]:
arr=random_sampling_LHS_np(10,500)
print(arr)

[[0.05041538 0.00511687 0.41681792 ... 0.37414489 0.84710859 0.46581621]
 [0.14037062 0.37784042 0.16754091 ... 0.44459251 0.76615093 0.16047981]
 [0.76179558 0.56954277 0.35530387 ... 0.83426663 0.43629266 0.02720996]
 ...
 [0.32877735 0.49447498 0.24085356 ... 0.6753207  0.5319209  0.19592004]
 [0.12569761 0.1060966  0.02587863 ... 0.39600835 0.60653143 0.00329924]
 [0.18613107 0.76148948 0.07404165 ... 0.5898645  0.26538611 0.97539246]]
